# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'natch' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for natch
	pod 'Parse'
	pod 'SVProgressHUD'
  target 'natchTests' do
    inherit! :search_paths
	pod 'Parse'
	pod 'SVProgressHUD'
  end

  target 'natchUITests' do
    inherit! :search_paths
	pod 'Parse'
	pod 'SVProgressHUD'
  end

end
